### PR TITLE
[DO NOT MERGE] Update code base to use EE8

### PR DESCRIPTION
**Pull request by barecode**
DO NOT MERGE THIS UNTIL Liberty buildback in IBM Bluemix Cloud Foundry supports EE 8 features.

### CODE REVIEW

**Comment by k8vance88** [comment]
We need to investigate whether IBM Bluemix Cloud Foundry supports EE 8 features.

**Comment by kinueng** [comment]
Please note that i discovered that the `server.xml` that is checked into the openliberty.io code base is not used by ibm cloud, currently.  I believe the liberty features are enabled by the manifest.yml
https://github.com/OpenLiberty/openliberty.io/blob/f98179b0222a312b3a2ec5cd3a001785ebef354c/manifest.yml#L67

There is a way to have IBM Cloud use the `server.xml`, but we currently do not utilize that feature.

**Comment by kinueng** [comment]
IBM Cloud is currently giving us Java 8 through the buildpack.  Here is a snippet of the logs from Travis taken from a recent build
```
Downloaded app package (43.1M)
-----> Liberty Buildpack Version: v3.31-20190423-1354
-----> Retrieving IBM 1.8.0_20190311 JRE (ibm-java-jre-8.0-5.31-pxa6480sr5fp31-20190311_03-cloud-unrestricted.tgz) ... (0.0s)
         Expanding JRE to .java ... (3.7s)
-----> Retrieving App Management 1.27.0_20171010-1200 (app-mgmt_v1.27-20171010-1200.zip) ... (0.0s)
         Expanding App Management to .app-management (0.2s)
-----> Retrieving com.ibm.ws.liberty-19.0.0.3-201904231354.tar.gz ... (0.0s)
         Installing archive ... (5.1s)
-----> Retrieving com.ibm.ws.liberty.ext-19.0.0.3-201904231354.tar.gz ... (0.0s)
         Installing archive ... (3.1s)
-----> Retrieving com.ibm.ws.liberty.javaee7-19.0.0.3-201904231354.tar.gz ... (0.0s)
         Installing archive ... (1.4s)
-----> Retrieving com.ibm.ws.liberty.javaee8-19.0.0.3-201904231354.tar.gz ... (0.0s)
         Installing archive ... (5.7s)
-----> Liberty buildpack is done creating the droplet
Exit status 0
```

**Comment by barecode** [comment]
@kin I believe you are correct re: manifest.yml - when I was trying to update the code base to use EE8 I had to fiddle with the manifest. @k8vance88 last I knew there was outstanding work to support EE8 but it looks like its there. A quick sample app using EE 8 only features should validate.

**Comment by steven1046** [comment]
The branch looks good on https://demo1-openlibertyio.mybluemix.net/ with no errors.

**Pull request merged**
