### PR TITLE
#2593 fixed

### PR DESCRIPTION
**Pull request by punitkr03**
Removed unnecessary Antora meta tag.

## Tested using browser:
- [x] Firefox (Desktop)
- [x] Safari (Desktop)
- [x] Chrome (Desktop)

### CODE REVIEW

**Comment by natalie-bernhard** [comment]
Hi, please change the base branch to draft instead of prod, or convert this to a draft PR and create a new, separate pull request into the draft branch.  Please refer to our wiki for details about our delivery process.

**Comment by punitkr03** [comment]
Hey, @natalie-bernhard base branch is changed to draft as requested.

**Review by natalie-bernhard — APPROVED** [review]

**Comment by steven1046** [comment]
@punitkr03, the code looks good. Can you please create a pull request from the same branch on your fork into `staging` to help proceed it to the main site?

**Comment by punitkr03** [comment]
Hey @steven1046 , I just created a pull request into the staging branch. Check it out.

**Pull request merged**
