### PR TITLE
Version links

### PR DESCRIPTION
**Pull request by navaneethsnair1**
## What was changed and why?
Link to the issue [here](https://github.com/OpenLiberty/openliberty.io/issues/3520)

## Tested using browser:
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)

## Did you test accessibility:
- [ ] IBM Equal Access Accessibilty Checker
- [ ] Jaws (only relevant for new UX flows)

### CODE REVIEW

**Comment by natalie-bernhard** [comment]
Did you test this change on draft? It doesn't seem to be working as far as I can see. Converting this PR to a draft PR until we can confirm the code works.

**Comment by navaneethsnair1** [comment]
It seems to be running fine when I tested.

**Comment by natalie-bernhard** [comment]
Can you paste an example link here of it working on the draft website?

**Comment by natalie-bernhard** [comment]
These commits were merged into staging but the actual changes were not.  Please create a new branch to work on this feature.

**Pull request merged**
