### PR TITLE
2895 language picker spacing

### PR DESCRIPTION
**Pull request by kinueng**
## Link GitHub issue
Issue #2895 

## Tested using browser:
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [x] Chrome (Desktop)

### CODE REVIEW

**Comment by kinueng** [comment]
I deleted one of the commits in the feature branch to clean up the code diff. I hope what is showing now is the intended changes to the code.

**Comment by kinueng** [comment]
This is what it looks like on ui-draft with zero blogs. Looks OK unless we need to wait to test with blogs using the full draft site.
image

**Comment by natalie-bernhard** [comment]
Waiting to see this on the full draft site just to double check that the UI does not change when the featured tags are loaded in

**Comment by kinueng** [comment]
This is what it looks like on ui-staging without the fix and zero blog posts
image

**Review by natalie-bernhard — APPROVED** [review]

**Pull request merged**
