### PR TITLE
Add blog about the Liberty Spring Boot Starter

### PR DESCRIPTION
**Pull request by tjwatson**
This can be published anytime, but it should be no later than Friday, December 1st

### CODE REVIEW

**Comment by kinueng** [comment]
Hey @tjwatson,

I changed this pull request to merge into the `development` branch.  When @lauracowen approves the blog content and merges this pull request into the `development` branch, the blog post will be published on our staging environment (https://openlibertydev.mybluemix.net/blog/).  The staging environment is where we make sure the website builds fine and the blog post is rendered as expected.

Once everything looks good, the blog post will be merged into `master` to publish on openliberty.io.

I will take care of most of the merging above.  I will reach out to you once the blog is on the staging so you can do a quick look before we push to openliberty.io.

**Comment by lauracowen** [comment]
Hi, looks good in general. Some minor comments:

* 'maven' should be 'Maven'.
* 'gradle' should be 'Gradle'.
* 'pom' should be 'POM' (or `pom.xml`)
* Typo 'porjects'
* I tend to put file names in backticks so they render with grey shading: eg build.gradle as `build.gradle`, `pom.xml`
* "An exclusion is needed for each starter your Spring Boot application depends on which transitively pulls in spring-boot-starter-tomcat." is a bit awkward to read. How about: "Add an exclusion for each starter that your Spring Boot application depends on that transitively pulls in spring-boot-starter-tomcat."
* "This prevents including the spring-boot-starter-tomcat in your application." <- I know what you mean but this is also a bit awkward. Can you just say "This excludes the spring-boot-starter-tomcat from your application." or "This prevents the spring-boot-starter-tomcat being included in your application."
* "...with the following:" -> "with the following code:" or "with the following XML:"
* In fact, "For maven projects this can be done with the following:" would be better as "For Maven projects, you can do this by adding the following code:" (or XML). Ditto for the Gradle version.
* Make headings 'sentence-style'. That is change "Include Liberty Spring Boot Starter" to "Include Liberty Spring Boot starter"; "Additional Open Liberty Components" to "Additional Open Liberty components" - like in a sentence, only capitalise names and the first word. Don't capitalise every word just because it's a heading.
* "ssl" to "SSL"
* "Open liberty has a modular runtime" to "Open Liberty has a modular runtime" (capital 'L')
* "Websocket" to "WebSocket"
* "These features can be enabled by" to "You can enable these features by" (Makes it clearer who would need to do the enabling. There might be other instances where this change is also relevant - basically always write 'actively' instead of in the more 'passive' way we get taught in Science lessons at school.) :)
* "Liberty specific configuration properties" to "Liberty-specific configuration properties"
* "If not specified a temporary directory will be used." to "If not specified a temporary directory is used." - unless the present tense just doesn't make sense (it usually does work fine), use the present tense as it's clearer and easier to read. Again, there might be other instances where this change is also relevant.
* "the Liberty logs are stored under a folder" <- should that be "under a folder in" or "under the folder"?
* "Once the application stops the base directory used by liberty will be deleted." to "When the application stops, the base directory used by Liberty is deleted." - "when" rather than "once" is a bit clearer for English-as-a-second language readers; comma after "stops" makes it easier to read; capital 'L'; present tense is easier to read.

All minor things but if you could make them (and check for other instances where the same changes apply - I've not marked them all), I'm happy with this. Thanks!

**Comment by tjwatson** [comment]
Thanks @lauracowen I made the requested changes in a follow on commit.  Can you merge this into development branch after a final review of the changes?

**Comment by kinueng** [comment]
Hi @tjwatson,
I rendered the blog post locally with your newest commit 91632e0 and 0c4f84c.

image

**Comment by kinueng** [comment]
The blog card looks like this
image

**Comment by tjwatson** [comment]
@kinueng  I guess we need to update the date for the day it actually gets posted?

**Comment by kinueng** [comment]
@tjwatson, I'll update the date before pushing to openliberty.io

**Comment by lauracowen** [comment]
Just saw the preview - 'Starter' should be lower-case (according to the rest of the post).

Also, I forgot the blog card displays the first paragraph. Really, that card should contain the point of the post (ie that it's about setting OL as the app server in the Spring Boot starter) - currently it doesn't actually tell you what the post is about.

**Pull request merged**
