### PR TITLE
Update to CSS with Hover Effect for .continued_text

### PR DESCRIPTION
**Pull request by martinyis**
## What was changed and why?
I have made changes to the CSS for the .continued_text class to introduce a hover effect. Here's a summary of the modifications:

Added a hover effect to the .continued_text class.
The text now transitions to a darker background color (#C95F22) when hovered over.
Please review the changes and let me know if you have any feedback or questions.

Thank you!
## Tested using browser:
- [ ] Chrome (Desktop)

### CODE REVIEW

**Comment by natalie-bernhard** [comment]
Hi @martinyis , can you please remove the automatic formatting from this commit?

**Comment by martinyis** [comment]
> Hi @martinyis , can you please remove the automatic formatting from this commit?

@natalie-bernhard I just removed the automatic formatting in recent commit!

**Comment by natalie-bernhard** [comment]
Hi @martinyis it seems you may have removed all of your changes.

**Comment by natalie-bernhard** [comment]
Closing after a month of no activity

**Pull request closed without merging**
