### PR TITLE
PR for MP OpenAPI 

### PR DESCRIPTION
**Pull request by arthurdm**
#### What was fixed?  (Issue # or description of fix)

Creating another PR, to go into the `master` branch's `_posts` (previous one went into the `development`'s branch's `_drafts`.

#### Were the changes tested on
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [X] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)
#### Running validation tools
- [ ] https://validator.w3.org/checklink
- [ ] https://validator.w3.org
- [ ] Dymanic Accessability Plugin (DAP)

### CODE REVIEW

**Comment by arthurdm** [comment]
thanks @lauracowen !    Review comments have been addressed.

**Comment by lauracowen** [comment]
@kinueng I'm happy for you to merge this. The changes Arthur has made have added the seo tags and extended the length slightly of the blog_description (which I think is the bit that controls what's displayed on the blog index page?). It's up to you if you want to preview on staging again. I think it *should* be okay to just push to master...

**Comment by steven1046** [comment]
@arthurdm the changes look good, but when i tested locally the image paths were not correct. Can you please move the blog images into a src/main/content/img/blog folder?

**Comment by arthurdm** [comment]
thanks for the feedback @steven1046 - it looks like my fork was out of sync and it hadn't picked up the new images in `src/main/content/img/blog`.  Should be all fixed now.

**Pull request merged**
