### PR TITLE
2226 caching noversion

### PR DESCRIPTION
**Pull request by Sreejith-Websphere**
#### Were the changes tested on
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [x] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)
#### Running validation tools
- [ ] https://validator.w3.org/checklink
- [ ] https://validator.w3.org
- [ ] IBM Equal Access Accessibility Checker (https://www.ibm.com/able/toolkit/verify/automated)
- [ ] Lighthouse (in Chrome dev tools)

### CODE REVIEW

**Comment by Sreejith-Websphere** [comment]
tested in draft
[
Screenshot 2022-04-07 at 1 38 01 PM
](url)

**Comment by Sreejith-Websphere** [comment]
tested in draft
Screenshot 2022-04-07 at 1 45 38 PM

**Comment by Sreejith-Websphere** [comment]
Screenshot 2022-04-07 at 1 45 56 PM

**Review by aknguyen7 — APPROVED** [review]

**Pull request merged**
