### PR TITLE
Starter none msg issue

### PR DESCRIPTION
**Pull request by Sreejith-Websphere**
#### What was fixed?  (Issue # or description of fix)

For https://github.com/openliberty/start.openliberty.io/issues/107

#### Were the changes tested on
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [x] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)
#### Running validation tools
- [ ] https://validator.w3.org/checklink
- [ ] https://validator.w3.org
- [ ] IBM Equal Access Accessibility Checker (https://www.ibm.com/able/toolkit/verify/automated)
- [ ] Lighthouse (in Chrome dev tools)

### CODE REVIEW

**Comment by Sreejith-Websphere** [comment]
tested in draft, no message is displayed when None is selected and its not setting to default values

Screenshot 2022-07-13 at 12 25 24 PM

**Comment by Sreejith-Websphere** [comment]
tested in draft, no message is displayed when None is selected and its not setting to default values

**Comment by Sreejith-Websphere** [comment]
tested in draft, no message is displayed when None is selected and its not setting to default values
Screenshot 2022-07-13 at 12 25 24 PM

**Comment by Sreejith-Websphere** [comment]
tested in draft, no message is displayed when None is selected and its not setting to default values
Screenshot 2022-07-13 at 12 25 24 PM

**Comment by Sreejith-Websphere** [comment]
tested in draft, no message is displayed when None is selected and its not setting to default values

**Comment by Sreejith-Websphere** [comment]
tested in draft, no message is displayed when None is selected and its not setting to default values

Screenshot 2022-07-13 at 12 25 24 PM

**Review by kinueng — APPROVED** [review]
LGTM

The new test cases were green when targeting the draft site.  Thank you for writing the tests!
image

**Comment by kinueng** [comment]
I will go ahead and merge this for you @Sreejith-Websphere

**Pull request merged**
