### PR TITLE
Revert "Revert "Update production""

### PR DESCRIPTION
**Pull request by natalie-bernhard**
Reverts OpenLiberty/openliberty.io#3056
Re-releasing fix to make copy code blocks accessible by screen reader

### CODE REVIEW

**Comment by steven1046** [comment]
Do we want to merge it into staging first (https://github.com/OpenLiberty/openliberty.io/compare/staging...revert-3056-revert-3039-staging) to make sure it builds on the staging site? I'm a little worried since the staging site has one of the extra copy icons on it at the moment.

**Comment by natalie-bernhard** [comment]
Deployed to staging and looks good @steven1046

**Comment by steven1046** [comment]
ok, can we merge staging into prod instead of the other branch?

**Comment by natalie-bernhard** [comment]
Yes, closing this PR

**Pull request closed without merging**
