### PR TITLE
Kevin's review comments

### PR DESCRIPTION
**Pull request by lauracowen**
Added Kevin's review comments.
Moved and renamed file to be published.
Fixed conflicts.

### CODE REVIEW

**Comment by steven1046** [comment]
@lauracowen 
Please change the images to 

image::/img/microservices-architecture.png[align="center",Diagram of a monolithic architecture with all applications hosted by a single app server versus three separate app servers each hosting a single microservice.,width=100%]
and
image::/img/microprofile13.png[align="center",Diagram of the components of MicroProfile 1.3.,width=100%]

so the images fit to screen in mobile view. Right now they're cut off because they're too large.

**Comment by kinueng** [comment]
We no longer need to do the work in @steven1046 comment above.  We put a change in that will manage the size of the images automatically in the blog posts.  This means asciidoc authors do not need to care about `width` properties in the `*.adoc` files that they deliver for blog posts.

See https://github.com/OpenLiberty/openliberty.io/pull/354

**Comment by kinueng** [comment]
Assigning to @steven1046 since he is currently handling how to get this PR into `master`

**Comment by steven1046** [comment]
I pulled @lauracowen 's branch and rebased it on development. The resulting commit will be delivered here: https://github.com/OpenLiberty/openliberty.io/pull/356

**Pull request closed without merging**
