### PR TITLE
H3 font issue

### PR DESCRIPTION
**Pull request by Sreejith-Websphere**
#### Were the changes tested on
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)
#### Running validation tools
- [ ] https://validator.w3.org/checklink
- [ ] https://validator.w3.org
- [ ] IBM Equal Access Accessibility Checker (https://www.ibm.com/able/toolkit/verify/automated)
- [ ] Lighthouse (in Chrome dev tools)

### CODE REVIEW

**Comment by Sreejith-Websphere** [comment]
Screenshot 2022-05-11 at 1 18 09 PM
Screenshot 2022-05-11 at 1 19 24 PM
tested in draft now no version page font not applied in feature pages

**Comment by Sreejith-Websphere** [comment]
Screenshot 2022-05-11 at 1 18 09 PM
Screenshot 2022-05-11 at 1 19 24 PM
tested in local, now no_version page css is not applied to feature pages

**Comment by kinueng** [comment]
Related to PR https://github.com/OpenLiberty/openliberty.io/pull/2640

**Review by kinueng — APPROVED** [review]
LGTM, my understanding is the fix for issue https://github.com/OpenLiberty/openliberty.io/issues/2226 was a bit too broad due to the CSS selector being scoped too wide.  This PR is to reduce the scope to only changing the `font-size` to the no version doc page.

**Comment by Sreejith-Websphere** [comment]
yes

**Pull request merged**
