### PR TITLE
Jakartaee redirect issue

### PR DESCRIPTION
**Pull request by Sreejith-Websphere**
#### Were the changes tested on
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)
#### Running validation tools
- [ ] https://validator.w3.org/checklink
- [ ] https://validator.w3.org
- [ ] IBM Equal Access Accessibility Checker (https://www.ibm.com/able/toolkit/verify/automated)
- [ ] Lighthouse (in Chrome dev tools)

### CODE REVIEW

**Comment by Sreejith-Websphere** [comment]
Screenshot 2022-03-30 at 12 10 59 PM

**Comment by Sreejith-Websphere** [comment]
Issue is JakartaEE was not redirecting
Screenshot 2022-03-30 at 12 26 06 PM

Fixed in draft

**Comment by Sreejith-Websphere** [comment]
Issue is jakartaee is not redirecting
Screenshot 2022-03-30 at 12 26 06 PM

**Comment by Sreejith-Websphere** [comment]
fixed in draft
Screenshot 2022-03-30 at 12 10 59 PM

**Review by aknguyen7 — DISMISSED** [review]

**Pull request merged**
