### PR TITLE
Header fixes

### PR DESCRIPTION
**Pull request by ellenwyllie**
#### Were the changes tested on
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [x] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)
#### Running validation tools
- [ ] https://validator.w3.org/checklink
- [ ] https://validator.w3.org
- [ ] Dymanic Accessability Plugin (DAP)

### CODE REVIEW

**Comment by kinueng** [comment]
Please make sure to minify the new svg file

**Comment by steven1046** [comment]
image

I think the navbar-collapse div is overlapping the white navbar slightly.

**Comment by steven1046** [comment]
The overlap seemed to only happen on my Mac on Chrome, and didn't occur on other user's machines.

**Comment by kinueng** [comment]
@steven1046, please re-review the new commits when you get a chance

**Comment by steven1046** [comment]
Will there be any more changes to this branch?

**Comment by ellenwyllie** [comment]
I'm making a new branch for the home page updates so you can go ahead and merge this one if it looks good.

**Comment by steven1046** [comment]
The title overlaps the text when you shrink the contribute or the community page:
image

**Comment by ellenwyllie** [comment]
I just updated the community and contribute pages to bootstrap 4 on a different branch. That should fix the overlapping issue. Initially I thought these pages were being deleted so I didn't update them.

**Pull request merged**
