### PR TITLE
Ver link

### PR DESCRIPTION
**Pull request by navaneethsnair1**
## What was changed and why?
Link to issue [here](https://github.com/OpenLiberty/openliberty.io/issues/3520)

Created a new PR to solve the issue of page not scrolling down to target location

## Tested using browser:
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)

## Did you test accessibility:
- [ ] IBM Equal Access Accessibilty Checker
- [ ] Jaws (only relevant for new UX flows)

### CODE REVIEW

**Comment by steven1046** [comment]
We need to make sure that links like https://openliberty.io/start/#gradle, https://openliberty.io/start/#maven, and https://openliberty.io/start/#docker still work. We can test those on draft.

**Review by steven1046 — APPROVED** [review]

**Review by natalie-bernhard — CHANGES_REQUESTED** [review]
This needs to be rebased

**Review by steven1046 — APPROVED** [review]

**Review by natalie-bernhard — CHANGES_REQUESTED** [review]
Requires additional rebase, my bad, I will complete the rebase

**Review by natalie-bernhard — APPROVED** [review]

**Comment by navaneethsnair1** [comment]
@steven1046 @natalie-bernhard 
I checked for ids like #maven, #gradle, #docker.
All 3 works fine

**Pull request merged**
