### PR TITLE
Static guide redesign implementation

### PR DESCRIPTION
**Pull request by kevinwlau**
…d off new redlines.

### CODE REVIEW

**Comment by kevinwlau** [comment]
Potential issues
	- inconsistency between static and interactive guides
	- - the duration and the short description sentence are swapped and the spacing is different

**Comment by kinueng** [comment]
Before I looked at the commits, I tested this branch on qa-guides.mybluemix.net and spotted some issues.

https://qa-guides.mybluemix.net/guides/docker.html

image

**Comment by kinueng** [comment]
I am closing this PR since there is still ongoing work for the redesign of the single guide view.

**Comment by kevinwlau** [comment]
Current mismatch between the new design mockup and this implementation: 
The `Contribute to this guide` and `Related guides` sections each have their own card in this implementation, but are grouped under `Great work! You’re done!` in the design.

**Comment by kinueng** [comment]
Fixes #92

**Pull request merged**
