### PR TITLE
Dockerfile for creating a docker image of openliberty.io

### PR DESCRIPTION
**Pull request by kinueng**
#### Were the changes tested on
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)
#### Running validation tools
- [ ] https://validator.w3.org/checklink
- [ ] https://validator.w3.org
- [ ] Dymanic Accessability Plugin (DAP)

### CODE REVIEW

**Comment by barecode** [comment]
@lauracowen I like the Dockerfile. Whats the command to run `docker` and mount in the local filesystem so things auto-rebuild based on local (out of container) changes?

**Comment by kinueng** [comment]
Hi @barecode,
This is the current state of things for the Dockerfile.  The steps below will change very soon due to the migration of blog files from this repo `OpenLiberty/openliberty.io` to `OpenLiberty/blogs`.  I'm also still a novice at managing a docker image (haven't dealt with versioning yet).

---

### Getting started with openliberty.io docker image instructions.
**Note: you must change the absolute path on the last command: `docker run`**
```
git clone https://github.com/OpenLiberty/openliberty.io.git
docker pull kinueng/openliberty.io
docker run --name jekyll -it -p 4000:4000 -v /Users/kueng/work/sandboxes/openliberty.io:/home/jekyll kinueng/openliberty.io
```

**Comment by barecode** [comment]
@kinueng awesome - the commands make sense. You can version Docker images by using  tags, but given this is still under active development, probably not worth worrying about for now :)

**Comment by steven1046** [comment]
> Hi @barecode,
> This is the current state of things for the Dockerfile. The steps below will change very soon due to the migration of blog files from this repo `OpenLiberty/openliberty.io` to `OpenLiberty/blogs`. I'm also still a novice at managing a docker image (haven't dealt with versioning yet).
> 
> ### Getting started with openliberty.io docker image instructions.
> **Note: you must change the absolute path on the last command: `docker run`**
> 
> ```
> git clone https://github.com/OpenLiberty/openliberty.io.git
> docker pull kinueng/openliberty.io
> docker run --name jekyll -it -p 4000:4000 -v /Users/kueng/work/sandboxes/openliberty.io:/home/jekyll kinueng/openliberty.io
> ```

We should reference these instructions somewhere if we need to use them.

**Comment by kinueng** [comment]
@steven1046 The instructions are still being development.  The instructions you see in this issue is the initial run and there are a lot more improvements that are needed before we want people to start using the container.

**Pull request merged**
