### PR TITLE
Incorporate feedback for FT 1.1 metrics blog post

### PR DESCRIPTION
**Pull request by Azquelt**

### CODE REVIEW

**Comment by kinueng** [comment]
Hi @Azquelt,
Will your

**Comment by kinueng** [comment]
Oh dear...sorry about all the alerts above. I pushed the wrong button.

**Comment by kinueng** [comment]
Hi @Azquelt,
Do you have any plans to move your documentation links starting with `https://github.com/Azquelt/...` to a GitHub organization like `OpenLiberty`?  I am just thinking about avoiding broken links if you ever decide to delete repositories from your personal GitHub.

**Comment by Azquelt** [comment]
I'm happy to move them if we have a place where we want to put samples like this.

I did ask at the time and it was suggested I put them in my own github for now with the possibility of having somewhere more central to put them later.

**Comment by kinueng** [comment]
I revisited the topic of checking for broken links this morning and learned...

We use a link checker scanner from the w3 organization to scan for broken links on openliberty.io. 
 Since GitHub tells web crawlers to go away in their `robots.txt`, I won't be able to use the link checker to validate any GitHub links :(.  Of course this isn't specific to your blog post @Azquelt, but for any link on openliberty.io.  So even if we move your samples to another GitHub repo, the scanner still cannot detect a deleted sample.

# Sample of a scan that shows the GitHub links
image

**Pull request merged**
