### PR TITLE
Blog title and orange url clickable

### PR DESCRIPTION
**Pull request by SteveSamJacob**
## Tested using browser:
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)

### CODE REVIEW

**Comment by steven1046** [comment]
Can you please remove the reformatting of index.html? I think using a formatter would be good, but we might want to do that as a separate PR in the future to not introduce any changes with reformatting a file.

**Comment by SteveSamJacob** [comment]
So i removed all my formatters but i dont why it still comes up all formatted.
Let me see if i can do something about it


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Steven Zvonek ***@***.***>
Sent: Wednesday, May 10, 2023 10:20:14 PM
To: OpenLiberty/openliberty.io ***@***.***>
Cc: Steve Sam Jacob ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [OpenLiberty/openliberty.io] Blog title and orange url clickable (PR #3159)

Can you please remove the reformatting of index. html? I think using a formatter would be good, but we might want to do that as a separate PR in the future to not introduce any changes with reformatting a file. — Reply to this email directly,
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Can you please remove the reformatting of index.html? I think using a formatter would be good, but we might want to do that as a separate PR in the future to not introduce any changes with reformatting a file.

**Comment by steven1046** [comment]
In visual studio settings, you can search for `on save` and there's a setting where it formats on every save of a file:

image

**Comment by SteveSamJacob** [comment]
Yes ive turned that off the last time you told me to unformat but it still comes up as formatted and whats weird is only certain files are formatted

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Steven Zvonek ***@***.***>
Sent: Wednesday, May 10, 2023 10:22:41 PM
To: OpenLiberty/openliberty.io ***@***.***>
Cc: Steve Sam Jacob ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [OpenLiberty/openliberty.io] Blog title and orange url clickable (PR #3159)

In visual studio settings, you can search for on save and there's a setting where it formats on every save of a file — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

In visual studio settings, you can search for on save and there's a setting where it formats on every save of a file

**Comment by steven1046** [comment]
Can we make the hover over color behaviors the same external blogs on the index.html page as we did for the blog.html page?

**Comment by SteveSamJacob** [comment]
Ill work on it but is there any way I can manually choose which blog appears on the index cause I can't see the changes unless index page shows an external blog

**Comment by steven1046** [comment]
You can remove limit:1 from index.html line 220 to see all of the blogs:
from
`{% for post in site.posts limit:1 %}`
to
`{% for post in site.posts %}`

**Comment by SteveSamJacob** [comment]
oh alright thanks

**Comment by SteveSamJacob** [comment]
edited home page too

**Comment by steven1046** [comment]
Looks good to me! We have to fix the conflicts in the files now, you can try using the github ui's `Resolve conflicts` button on this PR or also on your branch you can do `git fetch` and then `git merge origin/prod` and fix the merge conflicts and push them. The ui on this PR seems easier in this case. If you haven't seen this diff syntax:
image

It is showing you two versions of part of the file at once, and we have to remove one of them so probably keep the top half where it says blog_url and delete all of the ==== and <<<<< >>>>>

**Review by natalie-bernhard — APPROVED** [review]

**Pull request merged**
