### PR TITLE
Escape apostrophes in tweet text

### PR DESCRIPTION
**Pull request by ellenwyllie**
#### Were the changes tested on
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)
#### Running validation tools
- [ ] https://validator.w3.org/checklink
- [ ] https://validator.w3.org
- [ ] Dymanic Accessability Plugin (DAP)

### CODE REVIEW

**Comment by kinueng** [comment]
I am worried that we removed the encodeURIComponent completely.

**Comment by steven1046** [comment]
Does encodeURIComponent not encode an apostrophe?

**Comment by kinueng** [comment]
@steven1046 encodeURIComponent does not encode some special characters :(

```
A-Z a-z 0-9 - _ . ! ~ * ' ( )
```

**Comment by kinueng** [comment]
What about leveraging Liquid's encode?
https://shopify.github.io/liquid/filters/url_encode/

**Comment by steven1046** [comment]
@kinueng that didn't encode the apostrophe.

**Comment by ellenwyllie** [comment]
I guess the other option is to add back the encodeURIComponent and just remove the apostrophe

**Pull request closed without merging**
